"""Add custom KiCad file storage and source tracking to KiCadLibraryData

Revision ID: a327840bc5f7
Revises: e1925971c950
Create Date: 2025-09-27 15:29:39.741686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'a327840bc5f7'
down_revision: Union[str, None] = 'e1925971c950'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_custom_fields_name', table_name='custom_fields')
    op.drop_table('custom_fields')
    op.drop_index('ix_projects_name', table_name='projects')
    op.drop_table('projects')
    op.drop_index('idx_tags_name', table_name='tags')
    op.drop_index('ix_tags_name', table_name='tags')
    op.drop_table('tags')
    op.drop_index('idx_component_tags_component_id', table_name='component_tags')
    op.drop_index('idx_component_tags_tag_id', table_name='component_tags')
    op.drop_table('component_tags')
    op.drop_index('idx_stock_transactions_component_id', table_name='stock_transactions')
    op.drop_index('idx_stock_transactions_created_at', table_name='stock_transactions')
    op.drop_index('idx_stock_transactions_transaction_type', table_name='stock_transactions')
    op.drop_table('stock_transactions')
    op.drop_index('idx_components_category_id', table_name='components')
    op.drop_index('idx_components_category_name', table_name='components')
    op.drop_index('idx_components_component_type', table_name='components')
    op.drop_index('idx_components_created_at', table_name='components')
    op.drop_index('idx_components_manufacturer', table_name='components')
    op.drop_index('idx_components_name', table_name='components')
    op.drop_index('idx_components_package', table_name='components')
    op.drop_index('idx_components_part_number', table_name='components')
    op.drop_index('idx_components_search_text', table_name='components')
    op.drop_index('idx_components_type_manufacturer', table_name='components')
    op.drop_index('idx_components_updated_at', table_name='components')
    op.drop_index('idx_components_value', table_name='components')
    op.drop_index('ix_components_barcode_id', table_name='components')
    op.drop_index('ix_components_component_type', table_name='components')
    op.drop_index('ix_components_local_part_id', table_name='components')
    op.drop_index('ix_components_manufacturer', table_name='components')
    op.drop_index('ix_components_manufacturer_part_number', table_name='components')
    op.drop_index('ix_components_name', table_name='components')
    op.drop_index('ix_components_part_number', table_name='components')
    op.drop_index('ix_components_provider_sku', table_name='components')
    op.drop_table('components')
    op.drop_index('idx_purchases_created_at', table_name='purchases')
    op.drop_table('purchases')
    op.drop_table('meta_part_components')
    op.drop_index('idx_project_components_component_id', table_name='project_components')
    op.drop_index('idx_project_components_project_id', table_name='project_components')
    op.drop_table('project_components')
    op.drop_index('idx_categories_name', table_name='categories')
    op.drop_index('idx_categories_parent_id', table_name='categories')
    op.drop_index('ix_categories_name', table_name='categories')
    op.drop_table('categories')
    op.drop_table('substitutes')
    op.drop_table('api_tokens')
    op.drop_index('idx_component_provider_data_component_id', table_name='component_provider_data')
    op.drop_index('idx_component_provider_data_provider_id', table_name='component_provider_data')
    op.drop_index('ix_component_provider_cached_at', table_name='component_provider_data')
    op.drop_table('component_provider_data')
    op.drop_index('idx_purchase_items_component_id', table_name='purchase_items')
    op.drop_table('purchase_items')
    op.drop_index('idx_attachments_attachment_type', table_name='attachments')
    op.drop_index('idx_attachments_component_id', table_name='attachments')
    op.drop_table('attachments')
    op.drop_table('suppliers')
    op.drop_index('idx_custom_field_values_component_id', table_name='custom_field_values')
    op.drop_table('custom_field_values')
    op.drop_index('idx_storage_locations_name', table_name='storage_locations')
    op.drop_index('idx_storage_locations_parent_id', table_name='storage_locations')
    op.drop_index('ix_storage_locations_location_hierarchy', table_name='storage_locations')
    op.drop_index('ix_storage_locations_name', table_name='storage_locations')
    op.drop_index('ix_storage_locations_qr_code_id', table_name='storage_locations')
    op.drop_table('storage_locations')
    op.drop_table('component_data_providers')
    op.drop_index('idx_kicad_library_data_component_id', table_name='kicad_library_data')
    op.drop_table('kicad_library_data')
    op.drop_index('ix_component_locations_component_id', table_name='component_locations')
    op.drop_index('ix_component_locations_storage_location_id', table_name='component_locations')
    op.drop_table('component_locations')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_meta_parts_name', table_name='meta_parts')
    op.drop_table('meta_parts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta_parts',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('version', sa.VARCHAR(length=50), nullable=True),
    sa.Column('assembly_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('reference_designator', sa.VARCHAR(length=50), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_meta_parts'),
    sa.UniqueConstraint('name', 'version', name='uq_meta_part_name_version')
    )
    op.create_index('ix_meta_parts_name', 'meta_parts', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('hashed_password', sa.TEXT(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=False),
    sa.Column('must_change_password', sa.BOOLEAN(), nullable=False),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_users')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_table('component_locations',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('component_id', sa.VARCHAR(), nullable=False),
    sa.Column('storage_location_id', sa.VARCHAR(), nullable=False),
    sa.Column('quantity_on_hand', sa.INTEGER(), nullable=False),
    sa.Column('quantity_ordered', sa.INTEGER(), nullable=False),
    sa.Column('minimum_stock', sa.INTEGER(), nullable=False),
    sa.Column('location_notes', sa.TEXT(), nullable=True),
    sa.Column('unit_cost_at_location', sa.NUMERIC(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], name='fk_component_locations_component_id_components'),
    sa.ForeignKeyConstraint(['storage_location_id'], ['storage_locations.id'], name='fk_component_locations_storage_location_id_storage_locations'),
    sa.PrimaryKeyConstraint('id', name='pk_component_locations')
    )
    op.create_index('ix_component_locations_storage_location_id', 'component_locations', ['storage_location_id'], unique=False)
    op.create_index('ix_component_locations_component_id', 'component_locations', ['component_id'], unique=False)
    op.create_table('kicad_library_data',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('component_id', sa.VARCHAR(), nullable=False),
    sa.Column('symbol_library', sa.VARCHAR(length=255), nullable=True),
    sa.Column('symbol_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('footprint_library', sa.VARCHAR(length=255), nullable=True),
    sa.Column('footprint_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('model_3d_path', sa.TEXT(), nullable=True),
    sa.Column('kicad_fields_json', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], name='fk_kicad_library_data_component_id_components'),
    sa.PrimaryKeyConstraint('id', name='pk_kicad_library_data'),
    sa.UniqueConstraint('component_id', name='uq_kicad_library_data_component_id')
    )
    op.create_index('idx_kicad_library_data_component_id', 'kicad_library_data', ['component_id'], unique=False)
    op.create_table('component_data_providers',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('api_url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('api_key_encrypted', sa.TEXT(), nullable=True),
    sa.Column('is_enabled', sa.BOOLEAN(), nullable=False),
    sa.Column('priority', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_component_data_providers'),
    sa.UniqueConstraint('name', name='uq_provider_name')
    )
    op.create_table('storage_locations',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('parent_id', sa.VARCHAR(), nullable=True),
    sa.Column('location_hierarchy', sa.VARCHAR(length=500), nullable=False),
    sa.Column('qr_code_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['storage_locations.id'], name='fk_storage_locations_parent_id_storage_locations'),
    sa.PrimaryKeyConstraint('id', name='pk_storage_locations')
    )
    op.create_index('ix_storage_locations_qr_code_id', 'storage_locations', ['qr_code_id'], unique=False)
    op.create_index('ix_storage_locations_name', 'storage_locations', ['name'], unique=False)
    op.create_index('ix_storage_locations_location_hierarchy', 'storage_locations', ['location_hierarchy'], unique=False)
    op.create_index('idx_storage_locations_parent_id', 'storage_locations', ['parent_id'], unique=False)
    op.create_index('idx_storage_locations_name', 'storage_locations', ['name'], unique=False)
    op.create_table('custom_field_values',
    sa.Column('component_id', sa.VARCHAR(), nullable=False),
    sa.Column('field_id', sa.VARCHAR(), nullable=False),
    sa.Column('value', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], name='fk_custom_field_values_component_id_components'),
    sa.ForeignKeyConstraint(['field_id'], ['custom_fields.id'], name='fk_custom_field_values_field_id_custom_fields'),
    sa.PrimaryKeyConstraint('component_id', 'field_id', name='pk_custom_field_values')
    )
    op.create_index('idx_custom_field_values_component_id', 'custom_field_values', ['component_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('website', sa.VARCHAR(length=500), nullable=True),
    sa.Column('contact_email', sa.VARCHAR(length=255), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_suppliers'),
    sa.UniqueConstraint('name', name='uq_supplier_name')
    )
    op.create_table('attachments',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('component_id', sa.VARCHAR(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('file_size', sa.INTEGER(), nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('attachment_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('is_primary_image', sa.BOOLEAN(), nullable=False),
    sa.Column('thumbnail_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('display_order', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], name='fk_attachments_component_id_components'),
    sa.PrimaryKeyConstraint('id', name='pk_attachments')
    )
    op.create_index('idx_attachments_component_id', 'attachments', ['component_id'], unique=False)
    op.create_index('idx_attachments_attachment_type', 'attachments', ['attachment_type'], unique=False)
    op.create_table('purchase_items',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('purchase_id', sa.VARCHAR(), nullable=False),
    sa.Column('component_id', sa.VARCHAR(), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('unit_price', sa.NUMERIC(precision=10, scale=4), nullable=False),
    sa.Column('supplier_part_number', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], name='fk_purchase_items_component_id_components'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], name='fk_purchase_items_purchase_id_purchases'),
    sa.PrimaryKeyConstraint('id', name='pk_purchase_items')
    )
    op.create_index('idx_purchase_items_component_id', 'purchase_items', ['component_id'], unique=False)
    op.create_table('component_provider_data',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('component_id', sa.VARCHAR(), nullable=False),
    sa.Column('provider_id', sa.VARCHAR(), nullable=False),
    sa.Column('provider_part_id', sa.VARCHAR(length=255), nullable=False),
    sa.Column('datasheet_url', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('specifications_json', sqlite.JSON(), nullable=True),
    sa.Column('cached_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], name='fk_component_provider_data_component_id_components'),
    sa.ForeignKeyConstraint(['provider_id'], ['component_data_providers.id'], name='fk_component_provider_data_provider_id_component_data_providers'),
    sa.PrimaryKeyConstraint('id', name='pk_component_provider_data'),
    sa.UniqueConstraint('component_id', 'provider_id', name='uq_component_provider')
    )
    op.create_index('ix_component_provider_cached_at', 'component_provider_data', ['component_id', 'cached_at'], unique=False)
    op.create_index('idx_component_provider_data_provider_id', 'component_provider_data', ['provider_id'], unique=False)
    op.create_index('idx_component_provider_data_component_id', 'component_provider_data', ['component_id'], unique=False)
    op.create_table('api_tokens',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('hashed_token', sa.TEXT(), nullable=False),
    sa.Column('prefix', sa.VARCHAR(length=10), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('last_used_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_api_tokens_user_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_api_tokens'),
    sa.UniqueConstraint('hashed_token', name='uq_api_tokens_hashed_token')
    )
    op.create_table('substitutes',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('component_id', sa.VARCHAR(), nullable=False),
    sa.Column('substitute_component_id', sa.VARCHAR(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('compatibility_rating', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], name='fk_substitutes_component_id_components'),
    sa.ForeignKeyConstraint(['substitute_component_id'], ['components.id'], name='fk_substitutes_substitute_component_id_components'),
    sa.PrimaryKeyConstraint('id', name='pk_substitutes')
    )
    op.create_table('categories',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('parent_id', sa.VARCHAR(), nullable=True),
    sa.Column('sort_order', sa.INTEGER(), nullable=False),
    sa.Column('color', sa.VARCHAR(length=7), nullable=True),
    sa.Column('icon', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name='fk_categories_parent_id_categories'),
    sa.PrimaryKeyConstraint('id', name='pk_categories')
    )
    op.create_index('ix_categories_name', 'categories', ['name'], unique=False)
    op.create_index('idx_categories_parent_id', 'categories', ['parent_id'], unique=False)
    op.create_index('idx_categories_name', 'categories', ['name'], unique=False)
    op.create_table('project_components',
    sa.Column('project_id', sa.VARCHAR(), nullable=False),
    sa.Column('component_id', sa.VARCHAR(), nullable=False),
    sa.Column('quantity_allocated', sa.INTEGER(), nullable=False),
    sa.Column('quantity_used', sa.INTEGER(), nullable=False),
    sa.Column('quantity_reserved', sa.INTEGER(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('designator', sa.VARCHAR(length=50), nullable=True),
    sa.Column('unit_cost_at_allocation', sa.NUMERIC(precision=10, scale=4), nullable=True),
    sa.Column('total_cost_allocated', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('allocated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], name='fk_project_components_component_id_components'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_project_components_project_id_projects'),
    sa.PrimaryKeyConstraint('project_id', 'component_id', name='pk_project_components')
    )
    op.create_index('idx_project_components_project_id', 'project_components', ['project_id'], unique=False)
    op.create_index('idx_project_components_component_id', 'project_components', ['component_id'], unique=False)
    op.create_table('meta_part_components',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('meta_part_id', sa.VARCHAR(), nullable=False),
    sa.Column('component_id', sa.VARCHAR(), nullable=False),
    sa.Column('quantity_required', sa.INTEGER(), nullable=False),
    sa.Column('assembly_notes', sa.TEXT(), nullable=True),
    sa.Column('reference_designators', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], name='fk_meta_part_components_component_id_components'),
    sa.ForeignKeyConstraint(['meta_part_id'], ['meta_parts.id'], name='fk_meta_part_components_meta_part_id_meta_parts'),
    sa.PrimaryKeyConstraint('id', name='pk_meta_part_components'),
    sa.UniqueConstraint('meta_part_id', 'component_id', name='uq_meta_part_component')
    )
    op.create_table('purchases',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('supplier_id', sa.VARCHAR(), nullable=False),
    sa.Column('purchase_date', sa.DATE(), nullable=False),
    sa.Column('total_cost', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.VARCHAR(length=3), nullable=False),
    sa.Column('order_reference', sa.VARCHAR(length=255), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name='fk_purchases_supplier_id_suppliers'),
    sa.PrimaryKeyConstraint('id', name='pk_purchases')
    )
    op.create_index('idx_purchases_created_at', 'purchases', ['created_at'], unique=False)
    op.create_table('components',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('local_part_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('barcode_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('manufacturer_part_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('provider_sku', sa.VARCHAR(length=100), nullable=True),
    sa.Column('part_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(length=100), nullable=True),
    sa.Column('category_id', sa.VARCHAR(), nullable=True),
    sa.Column('component_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('value', sa.VARCHAR(length=50), nullable=True),
    sa.Column('package', sa.VARCHAR(length=50), nullable=True),
    sa.Column('average_purchase_price', sa.NUMERIC(precision=10, scale=4), nullable=True),
    sa.Column('total_purchase_value', sa.NUMERIC(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('specifications', sqlite.JSON(), nullable=True),
    sa.Column('custom_fields', sqlite.JSON(), nullable=True),
    sa.Column('provider_data', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='fk_components_category_id_categories'),
    sa.PrimaryKeyConstraint('id', name='pk_components')
    )
    op.create_index('ix_components_provider_sku', 'components', ['provider_sku'], unique=False)
    op.create_index('ix_components_part_number', 'components', ['part_number'], unique=False)
    op.create_index('ix_components_name', 'components', ['name'], unique=False)
    op.create_index('ix_components_manufacturer_part_number', 'components', ['manufacturer_part_number'], unique=False)
    op.create_index('ix_components_manufacturer', 'components', ['manufacturer'], unique=False)
    op.create_index('ix_components_local_part_id', 'components', ['local_part_id'], unique=False)
    op.create_index('ix_components_component_type', 'components', ['component_type'], unique=False)
    op.create_index('ix_components_barcode_id', 'components', ['barcode_id'], unique=False)
    op.create_index('idx_components_value', 'components', ['value'], unique=False)
    op.create_index('idx_components_updated_at', 'components', ['updated_at'], unique=False)
    op.create_index('idx_components_type_manufacturer', 'components', ['component_type', 'manufacturer'], unique=False)
    op.create_index('idx_components_search_text', 'components', ['name', 'part_number', 'manufacturer', 'notes'], unique=False)
    op.create_index('idx_components_part_number', 'components', ['part_number'], unique=False)
    op.create_index('idx_components_package', 'components', ['package'], unique=False)
    op.create_index('idx_components_name', 'components', ['name'], unique=False)
    op.create_index('idx_components_manufacturer', 'components', ['manufacturer'], unique=False)
    op.create_index('idx_components_created_at', 'components', ['created_at'], unique=False)
    op.create_index('idx_components_component_type', 'components', ['component_type'], unique=False)
    op.create_index('idx_components_category_name', 'components', ['category_id', 'name'], unique=False)
    op.create_index('idx_components_category_id', 'components', ['category_id'], unique=False)
    op.create_table('stock_transactions',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('component_id', sa.VARCHAR(), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=6), nullable=False),
    sa.Column('quantity_change', sa.INTEGER(), nullable=False),
    sa.Column('previous_quantity', sa.INTEGER(), nullable=False),
    sa.Column('new_quantity', sa.INTEGER(), nullable=False),
    sa.Column('reason', sa.TEXT(), nullable=False),
    sa.Column('reference_id', sa.VARCHAR(), nullable=True),
    sa.Column('reference_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('from_location_id', sa.VARCHAR(), nullable=True),
    sa.Column('to_location_id', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.VARCHAR(), nullable=True),
    sa.Column('user_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('batch_id', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], name='fk_stock_transactions_component_id_components'),
    sa.ForeignKeyConstraint(['from_location_id'], ['storage_locations.id'], name='fk_stock_transactions_from_location_id_storage_locations'),
    sa.ForeignKeyConstraint(['to_location_id'], ['storage_locations.id'], name='fk_stock_transactions_to_location_id_storage_locations'),
    sa.PrimaryKeyConstraint('id', name='pk_stock_transactions')
    )
    op.create_index('idx_stock_transactions_transaction_type', 'stock_transactions', ['transaction_type'], unique=False)
    op.create_index('idx_stock_transactions_created_at', 'stock_transactions', ['created_at'], unique=False)
    op.create_index('idx_stock_transactions_component_id', 'stock_transactions', ['component_id'], unique=False)
    op.create_table('component_tags',
    sa.Column('component_id', sa.VARCHAR(), nullable=False),
    sa.Column('tag_id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], name='fk_component_tags_component_id_components'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='fk_component_tags_tag_id_tags'),
    sa.PrimaryKeyConstraint('component_id', 'tag_id', name='pk_component_tags')
    )
    op.create_index('idx_component_tags_tag_id', 'component_tags', ['tag_id'], unique=False)
    op.create_index('idx_component_tags_component_id', 'component_tags', ['component_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('color', sa.VARCHAR(length=7), nullable=True),
    sa.Column('is_system_tag', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_tags')
    )
    op.create_index('ix_tags_name', 'tags', ['name'], unique=False)
    op.create_index('idx_tags_name', 'tags', ['name'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('version', sa.VARCHAR(length=20), nullable=True),
    sa.Column('client_project_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('budget_allocated', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('budget_spent', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('start_date', sa.DATETIME(), nullable=True),
    sa.Column('target_completion_date', sa.DATETIME(), nullable=True),
    sa.Column('actual_completion_date', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_projects')
    )
    op.create_index('ix_projects_name', 'projects', ['name'], unique=False)
    op.create_table('custom_fields',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('field_type', sa.VARCHAR(length=12), nullable=False),
    sa.Column('is_required', sa.VARCHAR(), nullable=False),
    sa.Column('default_value', sa.TEXT(), nullable=True),
    sa.Column('validation_rules', sa.TEXT(), nullable=True),
    sa.Column('options', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_custom_fields')
    )
    op.create_index('ix_custom_fields_name', 'custom_fields', ['name'], unique=False)
    # ### end Alembic commands ###