"""Add kicad_library_data table and fix missing relationships

Revision ID: 22648520e3e9
Revises: 002dae602c58
Create Date: 2025-09-27 05:58:16.086991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '22648520e3e9'
down_revision: Union[str, None] = '002dae602c58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tags_name', table_name='tags')
    op.drop_table('tags')
    op.drop_index('ix_projects_name', table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_storage_locations_location_hierarchy', table_name='storage_locations')
    op.drop_index('ix_storage_locations_name', table_name='storage_locations')
    op.drop_index('ix_storage_locations_qr_code_id', table_name='storage_locations')
    op.drop_table('storage_locations')
    op.drop_table('substitutes')
    op.drop_table('attachments')
    op.drop_table('component_tags')
    op.drop_index('ix_custom_fields_name', table_name='custom_fields')
    op.drop_table('custom_fields')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.drop_table('stock_transactions')
    op.drop_table('api_tokens')
    op.drop_index('ix_components_component_type', table_name='components')
    op.drop_index('ix_components_manufacturer', table_name='components')
    op.drop_index('ix_components_name', table_name='components')
    op.drop_index('ix_components_part_number', table_name='components')
    op.drop_table('components')
    op.drop_table('custom_field_values')
    op.drop_index('ix_categories_name', table_name='categories')
    op.drop_table('categories')
    op.drop_table('project_components')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_components',
    sa.Column('project_id', sa.VARCHAR(), nullable=False),
    sa.Column('component_id', sa.VARCHAR(), nullable=False),
    sa.Column('quantity_allocated', sa.INTEGER(), nullable=False),
    sa.Column('quantity_used', sa.INTEGER(), nullable=False),
    sa.Column('quantity_reserved', sa.INTEGER(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('designator', sa.VARCHAR(length=50), nullable=True),
    sa.Column('unit_cost_at_allocation', sa.NUMERIC(precision=10, scale=4), nullable=True),
    sa.Column('total_cost_allocated', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('allocated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], name='fk_project_components_component_id_components'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_project_components_project_id_projects'),
    sa.PrimaryKeyConstraint('project_id', 'component_id', name='pk_project_components')
    )
    op.create_table('categories',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('parent_id', sa.VARCHAR(), nullable=True),
    sa.Column('sort_order', sa.INTEGER(), nullable=False),
    sa.Column('color', sa.VARCHAR(length=7), nullable=True),
    sa.Column('icon', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name='fk_categories_parent_id_categories'),
    sa.PrimaryKeyConstraint('id', name='pk_categories')
    )
    op.create_index('ix_categories_name', 'categories', ['name'], unique=False)
    op.create_table('custom_field_values',
    sa.Column('component_id', sa.VARCHAR(), nullable=False),
    sa.Column('field_id', sa.VARCHAR(), nullable=False),
    sa.Column('value', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], name='fk_custom_field_values_component_id_components'),
    sa.ForeignKeyConstraint(['field_id'], ['custom_fields.id'], name='fk_custom_field_values_field_id_custom_fields'),
    sa.PrimaryKeyConstraint('component_id', 'field_id', name='pk_custom_field_values')
    )
    op.create_table('components',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('part_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(length=100), nullable=True),
    sa.Column('category_id', sa.VARCHAR(), nullable=True),
    sa.Column('storage_location_id', sa.VARCHAR(), nullable=True),
    sa.Column('component_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('value', sa.VARCHAR(length=50), nullable=True),
    sa.Column('package', sa.VARCHAR(length=50), nullable=True),
    sa.Column('quantity_on_hand', sa.INTEGER(), nullable=False),
    sa.Column('quantity_ordered', sa.INTEGER(), nullable=False),
    sa.Column('minimum_stock', sa.INTEGER(), nullable=False),
    sa.Column('average_purchase_price', sa.NUMERIC(precision=10, scale=4), nullable=True),
    sa.Column('total_purchase_value', sa.NUMERIC(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('specifications', sqlite.JSON(), nullable=True),
    sa.Column('custom_fields', sqlite.JSON(), nullable=True),
    sa.Column('provider_data', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name='fk_components_category_id_categories'),
    sa.ForeignKeyConstraint(['storage_location_id'], ['storage_locations.id'], name='fk_components_storage_location_id_storage_locations'),
    sa.PrimaryKeyConstraint('id', name='pk_components')
    )
    op.create_index('ix_components_part_number', 'components', ['part_number'], unique=False)
    op.create_index('ix_components_name', 'components', ['name'], unique=False)
    op.create_index('ix_components_manufacturer', 'components', ['manufacturer'], unique=False)
    op.create_index('ix_components_component_type', 'components', ['component_type'], unique=False)
    op.create_table('api_tokens',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.TEXT(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('hashed_token', sa.TEXT(), nullable=False),
    sa.Column('prefix', sa.TEXT(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('last_used_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hashed_token')
    )
    op.create_table('stock_transactions',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('component_id', sa.VARCHAR(), nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=6), nullable=False),
    sa.Column('quantity_change', sa.INTEGER(), nullable=False),
    sa.Column('previous_quantity', sa.INTEGER(), nullable=False),
    sa.Column('new_quantity', sa.INTEGER(), nullable=False),
    sa.Column('reason', sa.TEXT(), nullable=False),
    sa.Column('reference_id', sa.VARCHAR(), nullable=True),
    sa.Column('reference_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('from_location_id', sa.VARCHAR(), nullable=True),
    sa.Column('to_location_id', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.VARCHAR(), nullable=True),
    sa.Column('user_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('batch_id', sa.VARCHAR(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], name='fk_stock_transactions_component_id_components'),
    sa.ForeignKeyConstraint(['from_location_id'], ['storage_locations.id'], name='fk_stock_transactions_from_location_id_storage_locations'),
    sa.ForeignKeyConstraint(['to_location_id'], ['storage_locations.id'], name='fk_stock_transactions_to_location_id_storage_locations'),
    sa.PrimaryKeyConstraint('id', name='pk_stock_transactions')
    )
    op.create_table('users',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('username', sa.TEXT(), nullable=False),
    sa.Column('full_name', sa.TEXT(), nullable=True),
    sa.Column('hashed_password', sa.TEXT(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('1'), nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('must_change_password', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_table('custom_fields',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('field_type', sa.VARCHAR(length=12), nullable=False),
    sa.Column('is_required', sa.VARCHAR(), nullable=False),
    sa.Column('default_value', sa.TEXT(), nullable=True),
    sa.Column('validation_rules', sa.TEXT(), nullable=True),
    sa.Column('options', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_custom_fields')
    )
    op.create_index('ix_custom_fields_name', 'custom_fields', ['name'], unique=False)
    op.create_table('component_tags',
    sa.Column('component_id', sa.VARCHAR(), nullable=False),
    sa.Column('tag_id', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], name='fk_component_tags_component_id_components'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='fk_component_tags_tag_id_tags'),
    sa.PrimaryKeyConstraint('component_id', 'tag_id', name='pk_component_tags')
    )
    op.create_table('attachments',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('component_id', sa.VARCHAR(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('file_size', sa.INTEGER(), nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('attachment_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_primary_image', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('thumbnail_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('display_order', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], name='fk_attachments_component_id_components'),
    sa.PrimaryKeyConstraint('id', name='pk_attachments')
    )
    op.create_table('substitutes',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('component_id', sa.VARCHAR(), nullable=False),
    sa.Column('substitute_component_id', sa.VARCHAR(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('compatibility_rating', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], name='fk_substitutes_component_id_components'),
    sa.ForeignKeyConstraint(['substitute_component_id'], ['components.id'], name='fk_substitutes_substitute_component_id_components'),
    sa.PrimaryKeyConstraint('id', name='pk_substitutes')
    )
    op.create_table('storage_locations',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('parent_id', sa.VARCHAR(), nullable=True),
    sa.Column('location_hierarchy', sa.VARCHAR(length=500), nullable=False),
    sa.Column('qr_code_id', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['storage_locations.id'], name='fk_storage_locations_parent_id_storage_locations'),
    sa.PrimaryKeyConstraint('id', name='pk_storage_locations')
    )
    op.create_index('ix_storage_locations_qr_code_id', 'storage_locations', ['qr_code_id'], unique=False)
    op.create_index('ix_storage_locations_name', 'storage_locations', ['name'], unique=False)
    op.create_index('ix_storage_locations_location_hierarchy', 'storage_locations', ['location_hierarchy'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=9), nullable=False),
    sa.Column('version', sa.VARCHAR(length=20), nullable=True),
    sa.Column('client_project_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('budget_allocated', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('budget_spent', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('start_date', sa.DATETIME(), nullable=True),
    sa.Column('target_completion_date', sa.DATETIME(), nullable=True),
    sa.Column('actual_completion_date', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_projects')
    )
    op.create_index('ix_projects_name', 'projects', ['name'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('color', sa.VARCHAR(length=7), nullable=True),
    sa.Column('is_system_tag', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_tags')
    )
    op.create_index('ix_tags_name', 'tags', ['name'], unique=False)
    # ### end Alembic commands ###