name: "Release Please"

"on":
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  packages: write      # For release workflow to push Docker images
  issues: write        # For release workflow notifications
  actions: write       # For release workflow cache

jobs:
  release-please:
    name: "Create or Update Release PR"
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}

    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: python

  trigger-release:
    name: "Trigger Release Workflow"
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created == 'true' }}
    uses: ./.github/workflows/release.yml
    with:
      tag_name: ${{ needs.release-please.outputs.tag_name }}
    permissions:
      contents: write
      packages: write
      issues: write
      actions: write
    secrets: inherit
