name: "Release Please"

# This workflow automates version management and releases:
# 1. Monitors commits on main for conventional commits (feat:, fix:, docs:, etc.)
# 2. Creates/updates a release PR with:
#    - Bumped version in pyproject.toml
#    - Updated CHANGELOG.md
#    - Generated release notes
# 3. When the release PR is merged:
#    - Creates a git tag (e.g., v0.3.1)
#    - Creates a GitHub release with release notes
#    - Builds and uploads release artifacts (backend, frontend, source)
# 4. The tag push triggers the release.yml workflow for Docker/docs deployment

"on":
  push:
    branches: [main]

permissions:
  contents: write      # For creating releases and tags
  pull-requests: write # For creating/updating release PRs

jobs:
  release-please:
    name: "Create or Update Release PR"
    runs-on: ubuntu-latest

    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: python

      - name: Summary
        if: ${{ steps.release.outputs.release_created == 'true' }}
        run: |
          cat >> $GITHUB_STEP_SUMMARY << EOF
          # ✅ Release ${{ steps.release.outputs.tag_name }} Created

          Release Please has created:
          - Git tag: \`${{ steps.release.outputs.tag_name }}\`
          - GitHub release with release notes
          - Updated CHANGELOG.md

          The release.yml workflow will now:
          - Build and publish Docker images
          - Deploy versioned documentation

          View the release: https://github.com/${{ github.repository }}/releases/tag/${{ steps.release.outputs.tag_name }}
          EOF
